# Generated by Django 3.2.9 on 2021-11-19 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_rename_reated_review_rated'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='like_cnt',
            field=models.IntegerField(default=0),
        ),
    ]
